django_intro/app/urls.py
from django.urls import path

from . import views

app_name = 'app'

# urlpatterns = [
#     # ex: /app/
#     path('', views.index, name='index'),
#     # ex: /app/5/
#     path('<int:pk>/', views.detail, name='detail'),
#     # ex: /app/5/results/
#     path('<int:pk>/results/', views.results, name='results'),
#     # ex: /app/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

django_intro/django_intro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

django_intro/app/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
       return self.choice_text

django_intro/app/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {
#         'latest_question_list': latest_question_list,
#         'message' : "(Home Page) Hello, world. You're at the App's index."
#     }
#     # template = loader.get_template('app/index.html')
#     # return HttpResponse(template.render(context, request))
#     return render(request, 'app/index.html', context)


# def detail(request, question_id):
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist")
#     # return render(request, 'app/detail.html', {'question': question})

#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'app/detail.html', {'question': question})


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'app/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'app/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('app:results', args=(question.id,)))



class IndexView(generic.ListView):
    template_name = 'app/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'app/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'app/results.html'

django_intro/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django Intro.! (APP)</title> 
</head>

<body >
    <!-- {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}"> -->
    <link rel="stylesheet" type="text/css" href="/static/app/style.css">
    <p>
        {% block content %}

        {% endblock %}
    </p>
</body>
</html>

django_intro/templates/app/detail.html
{% extends './base.html' %}

{% block content %}

    <!--h1>{{ question.question_text }}</h1>
    
    <ul>
    <h3>Choices</h3>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
    </ul-->

<h1>{{ question.question_text }}</h1>
<ul>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'app:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        {% if question.choice_set.all %}
        <input type="submit" value="Vote">
        {%else%}
            <p> No choices available to vote.!</p>
        {% endif %}
    </form>
</ul>
<br><br><a href="{% url 'app:index' %}">Back to Questions</a>
{% endblock %}

django_intro/templates/app/index.html
{% extends './base.html' %}
{% block content %}

    <h1 id="main_header">(Home Page) Hello, world. You're at the App's index.</h1>
    <ul class="question_list">
    {% if latest_question_list %}
        
        {% for question in latest_question_list %}
            <!--li><a href="/app/{{ question.id }}/">{{ question.question_text }}</a></li-->
            <li><a href="{% url 'app:detail' question.id %}">
                    {{ question.question_text }}</a> </li>
            <br>
        {% endfor %}
       
    {% else %}
        <p>No App(Question list) are available.</p>
    {% endif %}
    </ul>

{% endblock %}

django_intro/templates/app/results.html
{% extends './base.html' %}

{% block content%}
<h1 style="font-size: 1.5cm;">{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'app:detail' question.id %}">Vote again?</a>

{% endblock%}